name: Type Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript check
        run: npx tsc --noEmit
